# Generated by Django 4.2.13 on 2024-06-23 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sede', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, unique=True, verbose_name='codigo')),
                ('sexo', models.BooleanField(null=True, verbose_name='sexo')),
                ('sedeID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sede.sede', verbose_name='sede')),
            ],
        ),
    ]
