# Generated by Django 4.2.13 on 2024-06-24 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sede', '0001_initial'),
        ('edificio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='sedeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='edificios', to='sede.sede', verbose_name='sede'),
        ),
    ]
