# Generated by Django 4.2.13 on 2024-06-25 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edificio', '0002_alter_edificio_sedeid'),
        ('dormitorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitorio',
            name='edificioID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dormitorios', to='edificio.edificio', verbose_name='edificio'),
        ),
    ]
